### ISSUE TITLE
Instead of policies it provides a config.yml

### ISSUE THREAD

**Issue by EliuX** [open-policy-agent/example-api-authz-python#1]
It would be nice some rego policies be added as code and indicated in the README instructions as parameter of the *opa* executable. The rego policies would be  applicable to the business logic of the app, to fully test this example project. Maybe a `granted access` and a `denied access` curl request samples would also be a good addition.

**Comment by tsandall** [comment]
Thanks for filing the issue! Pushed changes that show how to test locally.
